### ISSUE TITLE
how  to add keywords 

### ISSUE THREAD

**Issue by saivasanth** [gbateson/moodle-qtype_essayautograde#1]
Hi,
i have installed your essayautograde in my moodle 3.3 . its working fine . i am not able to set key words for my auto grading . 

how to set list of key words to check while auto grading ?

thanks in advance

**Comment by gbateson** [comment]
Hi,
I'm afraid I don't understand your question.
Specifically, what do you mean by "key words" and "auto grading"?

**Comment by saivasanth** [comment]
sorry.
i just want to know " the presence of one or more target phrases in the response"

how to set my target phrases. ?

**Comment by gbateson** [comment]
Oh, I see. You click the button marked, "Add another target phrase".

**Comment by saivasanth** [comment]
yes . got it thanks
