### ISSUE TITLE
Fool-proofing the target phrases

### ISSUE THREAD

**Issue by germanvaleroelizondo** [gbateson/moodle-qtype_essayautograde#10]
Hi Gordon, 

A comma must be followed by a space in order to work as an OR operator inside target phrases.

I have been playing with your Essay(auto-grade) plugin and maybe you can make it a bit more fool-proof when the teacher inputs the target phrases.

You can either, change the string "The target phrase can be a single phrase or a list of phrases separated by either a comma "," or the word "OR" (upper case)"

into ... 'a comma followed by one space ", " or the word "OR " followed by one space (upper case)"

or you can modify your code, so that a space is no longer needed after a comma or an 'OR' is entered in this field.

Thanks in advance.

**Comment by gbateson** [comment]
Thanks German. I have modified the code so that a comma that has no space preceding or following it can also be used to denote a list of items in a target phrase.

**Comment by germanvaleroelizondo** [comment]
Thank you Gordon.

Your moodle-qtype_essayautograde plugin keeps getting better.

Will you submit it to the Moodle plugins database in the near future ?
