### ISSUE TITLE
Publish plugin to Moodle plugin database

### ISSUE THREAD

**Issue by rlorenzo** [gbateson/moodle-qtype_essayautograde#13]
We are installing and testing out this plugin in our Moodle instance, but I was wondering why this plugin could not be found in the Moodle plugin database:

https://moodle.org/plugins/?q=Essay%20type:qtype

Having it in the official plugin database will alert us if there is a new version available.

**Comment by gbateson** [comment]
I haven't put it in the Moodle plugin database yet because it has not reached the top of my todo list.
I intend to add it at some point; maybe over the winter break.

**Comment by gbateson** [comment]
I have entered the qtype_essayautograde plugin into the plugins database on Moodle.org. It is currently waiting review. In my experience, it can take several weeks until a plugin reaches the head of the queue and is reviewed.
If (When?) is it accepted, it will become available on the following URL:
https://moodle.org/plugins/qtype_essayautograde

**Comment by germanvaleroelizondo** [comment]
+1

**Comment by gbateson** [comment]
Good news. This plugin has been accepted into the plugins repository on Moodle.org:
https://moodle.org/plugins/view.php?plugin=qtype_essayautograde

Thanks very much to all concerned :-)
