### ISSUE TITLE
Travis implementation

### ISSUE THREAD

**Issue by ak4t0sh** [gbateson/moodle-qtype_essayautograde#17]
I see that you have a .travis.yml file but it seems that you do not use it for this repo.

To enable it : 
Go to https://travis-ci.org/gbateson
Flick the switch for this repo.

then on every commit you make to github it will fire off a request to travis to run the tests in .travis.yml and will give you traffic lights beside each commit and generate a report.

Also I noticed you test it against MOODLE_34_STABLE, MOODLE_35_STABLE,and master. You should add MOODLE_36_STABLE.

please note - this is not a blocker for approval in the plugins db but would be nice to add at some point.

**Comment by gbateson** [comment]
Thanks very much for this feedback.
 I have added MOODLE_36_STABLE to the .travis.yml file and enable this plugin on travis-ci.org.
