### ISSUE TITLE
move language pack to AMOS

### ISSUE THREAD

**Issue by ak4t0sh** [gbateson/moodle-qtype_essayautograde#18]
Once #13 will be closed the `es` and `es_mx` pack should be moved away and submitted to AMOS.

https://lang.moodle.org/
https://docs.moodle.org/dev/AMOS_manual

please note - this is not a blocker for approval in the plugins db but would be nice to add at some point.

**Comment by gbateson** [comment]
Thanks. I've submitted the lang files to AMOS for review.

**Comment by germanvaleroelizondo** [comment]
The es_mx translations have been reviewed and approved in AMOS.

**Comment by germanvaleroelizondo** [comment]
Please close this issue. 
The international Spanish language pack maintainers usually take a very long time to process contributed translations :(

**Comment by gbateson** [comment]
You're everywhere German. Nice work and thanks!

**Comment by germanvaleroelizondo** [comment]
This plugin has also been translated into portuguese in AMOS :)

**Comment by dinism** [comment]
> This plugin has also been translated into portuguese in AMOS :)

I made it.
