### ISSUE TITLE
copyrights

### ISSUE THREAD

**Issue by ak4t0sh** [gbateson/moodle-qtype_essayautograde#19]
A lot of files have copyrights from `qtype_essay`. (For example : [lib.php#22](https://github.com/gbateson/moodle-qtype_essayautograde/blob/master/lib.php#L22)) 
https://docs.moodle.org/dev/Plugin_contribution_checklist#Copyrights

**Comment by gbateson** [comment]
The copyrights have been standardized to the Plugin contribution checklist.
Thanks for the heads up!
