### ISSUE TITLE
sentences counter handle only dots

### ISSUE THREAD

**Issue by ak4t0sh** [gbateson/moodle-qtype_essayautograde#21]
Currently sentences counter only support dots. I think exclamation and interrogation marks (! and ?) should be handled too. :)

![image](https://user-images.githubusercontent.com/2222386/54373282-442a7400-467d-11e9-9b2e-8e679eb4fa82.png)

**Comment by gbateson** [comment]
I ave updated the sentence counter to detect exclamation marks and question marks too.
Thank you for alerting me to this improvement.
