### ISSUE TITLE
PT translation

### ISSUE THREAD

**Issue by dinism** [gbateson/moodle-qtype_essayautograde#25]
Hi
I translated this strings in **AMOS**:
$string['phrasecasesensitiveno'] = 'Match is case-insensitive';
$string['phrasecasesensitiveyes'] = 'Match is case-sensitive.';
$string['phrasefullmatchno'] = 'Match full or partial words.';
$string['phrasefullmatchyes'] = 'Match full words only.';

But i **can't find it in plugin**!
![imagem](https://user-images.githubusercontent.com/14828021/57329608-08a3a780-710c-11e9-9514-ece8f8079dbb.png)
![imagem](https://user-images.githubusercontent.com/14828021/57330064-ee1dfe00-710c-11e9-9c35-b31c727a5b95.png)

**Comment by gbateson** [comment]
Thank you Dinism, for adding translating these strings.
They do not yet appear in the interface, but they will appear soon.
You can see them waiting to be uncommented in the main settings form for this plugin (see around lines 260-266 and 596-609 in the following file)
https://github.com/gbateson/moodle-qtype_essayautograde/blob/master/edit_essayautograde_form.php

**Comment by gbateson** [comment]
Here's a screenshot of how those phrases will be used.
![EAG target phases](https://user-images.githubusercontent.com/799312/57353890-e4e07000-71a4-11e9-9b3d-fb0550caf29f.png)

**Comment by dinism** [comment]
Thanks.

**Comment by gbateson** [comment]
Hi Dinism and German,
Thanks for all your hard work translating the strings for the "Essay (auto-grade)" question type.
I will try to find a sponsor for the work to add the case-sensitive and full-match functionality, and then your strings will be available to all.
