### ISSUE TITLE
Not saving draft

### ISSUE THREAD

**Issue by campbelljapan** [gbateson/moodle-qtype_essayautograde#28]
Gordon,
I'm not sure if this is an issue, but we have students say that they have done their essay, but then there is nothing submitted. In the most recent case the student started working on her essay and from looking at the logs she never clicked submit. In the assignment module it is always saving a draft, so even if a student doesn't click submit before the deadline I believe there is something saved. Is this the case with the essay auto grade question type? If not, is it something that could be added? Here is a screen shot of the log window. [essay autograde log](https://user-images.githubusercontent.com/49626688/59474430-bc255780-8e81-11e9-985f-87e60d68e371.png).

Also I'm not sure what this means and if has anything to do with problem.:

> 
![image](https://user-images.githubusercontent.com/49626688/59474525-2dfda100-8e82-11e9-8d0b-44470050c15c.png)

**Comment by gbateson** [comment]
I think the HTML editor saves automatically.
Please check whether she was editing with or without the editor.

**Comment by campbelljapan** [comment]
The question response option is set to HTML editor. Can the student override this?

**Comment by gbateson** [comment]
It can be overridden in a user's editor preferences. Please could you check that.

**Comment by campbelljapan** [comment]
I logged in as that student from my admin account and it looks like the HTML editor is on, at least by looking at the essay for this week's homework.

**Comment by gbateson** [comment]
It looks as though she never submitted the attempt then.
I wonder what happens if you start an Essay question and then just abandon that Quiz attempt?

**Comment by campbelljapan** [comment]
I have got an answer back from the student and she said she was able to see the HTML editor, but she didn't use it. I will test the idea of letting a quiz time out without submitting and see what happens.

**Comment by gbateson** [comment]
Thanks. I don't understand "she was able to see the HTML editor, but she didn't use it"
If the HTML editor was displayed to her in the Essay (auto-grade) question, how did she type in her essay without using the editor?

**Comment by campbelljapan** [comment]
She meant that she didn’t use the bold or italics tools, but she could see them. I also saw where the user can change the default editor, but none of the students are tech savvy enough to find the feature in Moodle.

David Campbell
Assistant Professor

**Comment by gbateson** [comment]
Thanks. 

Another think to check is the behavior in the Assignment module. You mentioned earlier that it is always saving a draft, so even if a student doesn't click submit before the deadline I believe there is something saved. 

Could you check what happens if the student begins to type an answer to an Assignment, but then just uses the back button to get out, or closes the window, and logs off the computer. Does that text later appear as the submitted answer? If the student goes back to the assignment, does the text appear in the HTML editor?

**Comment by campbelljapan** [comment]
Gordon,
I did a test with the auto grade and the assignment. The auto grade does save a draft even when the student doesn’t click save or submit. When the deadline passes whatever has been entered in the editing window is submitted and graded. 

The assignment module saves a draft as the student is working at that time, but they need to save before navigating away from the page. They do get a warning message asking if they want to leave the page. Nothing is saved if the don’t click the submit button before the deadline. 

David Campbell

**Comment by gbateson** [comment]
Thanks for confirming David.
It becomes even more of a puzzle then how the student who originally reported this issue was able to type something in but not have it auto-saved, and then auto-submitted.

**Comment by campbelljapan** [comment]
She may have just been trying to cover for missing the deadline. I will definitely be more skeptical of future claims that they had written their essay, but it wasn’t saved. 

One other thing I might check is what happens with copying something from MS Word and pasting it into the editing window.

David Campbell
Assistant Professor

**Comment by gbateson** [comment]
David,
any more news on the issue of students reporting that "Essay (auto-grade)" doesn't save the draft essay?
I'd like to close the ossue now, but feel free to reopen it if your students continue to have problems.
