### ISSUE TITLE
Error when importing demo questions from https://bateson.kochi-tech.ac.jp/34

### ISSUE THREAD

**Issue by germanvaleroelizondo** [gbateson/moodle-qtype_essayautograde#3]
Hi Gordon,

I installed a new Moodle 3.5.1+ (Build: 20180727) local server. 
I added the order qtype from Moodle database and your Esssay autograde plugin.

I can re-create your demo Essay autograde question without any problems. It works beautifully and I will be testing the Spanish translations with it, BUT...

When I tried to import the demo questions, I got the following error:

Parsing questions from import file.
Importing 5 questions from file

1. Write an essay - or use the one below if you like ;-)

2. Write a short paragraph of 50 words or more about your summer vacation. Try to include the following phrases: * First * Next OR Then * Finally OR In the end If you will get special bonus points, if you use ALL of the above phrases

Error writing to database

More information about this error
Debug info: Incorrect integer value: 'T' for column 'responsetemplateformat' at row 1
INSERT INTO mdl_qtype_essayautograde_options (questionid,responseformat,responserequired,responsefieldlines,attachments,attachmentsrequired,graderinfo,graderinfoformat,responsetemplate,responsetemplateformat,enableautograde,itemtype,itemcount,showfeedback,showcalculation,showtextstats,textstatitems,showgradebands,addpartialgrades,showtargetphrases,correctfeedback,correctfeedbackformat,partiallycorrectfeedback,partiallycorrectfeedbackformat,incorrectfeedback,incorrectfeedbackformat) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
[array (
0 => 4,
1 => 'editorfilepicker',
2 => '1',
3 => '5',
4 => '0',
5 => '0',
6 => '',
7 => 0,
8 => 'T',
9 => 'T',
10 => '1',
11 => '2',
12 => '50',
13 => '3',
14 => '0',
15 => '2',
16 => NULL,
17 => '0',
18 => '1',
19 => '0',
20 => '<',
21 => '<',
22 => '<',
23 => '<',
24 => '<',
25 => '<',
)]
Error code: dmlwriteexception
Stack trace:

    line 489 of \lib\dml\moodle_database.php: dml_write_exception thrown
    line 1329 of \lib\dml\mysqli_native_moodle_database.php: call to moodle_database->query_end()
    line 1375 of \lib\dml\mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
    line 147 of \question\type\essayautograde\questiontype.php: call to mysqli_native_moodle_database->insert_record()
    line 425 of \question\format.php: call to qtype_essayautograde->save_question_options()
    line 123 of \question\import.php: call to qformat_default->importprocess()

**Comment by gbateson** [comment]
The error is caused by the fact that this plugin does not currently support import/export of XML file.
I think if you try export/import of GIFT file format, you will have more success.

**Comment by gbateson** [comment]
I have added XML import/export to this plugin.
Please regenerate any XML files you created using earlier versions of this plugin. The new versions will work as expected.

**Comment by germanvaleroelizondo** [comment]
Thanks Gordon.
I will re-test and report back.
