### ISSUE TITLE
Not saving work when "Each attempt builds on the last"

### ISSUE THREAD

**Issue by donhinkelman** [gbateson/moodle-qtype_essayautograde#30]
Great plugin, Gordon, and the feedback format is greatly improved from early versions. I gave this question type a workout and here is one of two issues I found today.  When I check "Each attempt builds on the last" in the overall Quiz settings, I expected that each time I do an essay question, the previous work I did will be there to start with. However, each time I re-attempt an essay (multiple tries turned on), I find the HTML box is blank and I must recreate the text from zero. I am using the latest Essay Autograde, Moodle 3.7, and Firefox browser.

**Comment by donhinkelman** [comment]
I tried again logged as a specific enrolled student and my re-attempt kept the old data OK. So maybe the issue I reported above only occurs when I take the quiz as a teacher doing a review.

**Comment by donhinkelman** [comment]
I tested again, and when I log in as a specifice student the old data is moved to the next attempt as expected when set as "Each attempt builds on the last".  The issue I initially found only occurs for a teacher login. I will close this issue.

**Comment by gbateson** [comment]
Don, thanks for testing. I'll close this issue now.
