### ISSUE TITLE
Plagiarism plugin connection

### ISSUE THREAD

**Issue by koenr** [gbateson/moodle-qtype_essayautograde#34]
Hi Gordon,
You might be interested in following https://tracker.moodle.org/browse/MDL-32226
It's about a new hook to check essay questions against installed plagiarism detection plugins. 
Thank you for this fantastic question type.
Koen

**Comment by gbateson** [comment]
Hi Koen,
thanks for this tip! I added some calls to the "plagiarism_get_links()" function.
I don't have any plagiarism plugins installed, but maybe it will help someone who does ;-)
Kind regards
Gordon
