### ISSUE TITLE
How to do?

### ISSUE THREAD

**Issue by dinism** [gbateson/moodle-qtype_essayautograde#35]
Thanks for the plugin. GREAT WORK. 
Using release 2020-07-15 (90) in Moodle 3.9.1
I want a question where students MUST submit 1 required file PDF (max 2) and i want a answer with some words.
5% of grade for submitting the file and the rest is for the answer.
How to setup the question? Is it possible?
![imagem](https://user-images.githubusercontent.com/14828021/87860042-fc32f580-c931-11ea-9d8b-73f4a59a3ec5.png)
**Take a look to COUNTER. Submited with answer and 1 file.**
![imagem](https://user-images.githubusercontent.com/14828021/87860242-be36d100-c933-11ea-9d5d-914207e6d31f.png)
![imagem](https://user-images.githubusercontent.com/14828021/87860245-c68f0c00-c933-11ea-8dc6-d7c59672dc4d.png)
**Submited with answer an NO file**
![imagem](https://user-images.githubusercontent.com/14828021/87860250-cdb61a00-c933-11ea-8568-c3e3311601d9.png)
![imagem](https://user-images.githubusercontent.com/14828021/87860253-d3136480-c933-11ea-92dd-76b4d8ad5d0a.png)

**Comment by gbateson** [comment]
Thank you for reporting this issue.
The new "files" functionality does not seem to be working well for you. Sorry about that.
Because the "Type of countable items" is set to "Files", then the phrases and words are ignored.
So, please split this question into TWO questions: one to require the pdf file, and another to require the word and target phrases.

**Comment by dinism** [comment]
Is it possible have a question like i want? File and answer? If yes, what i'm doing wrong?
When the count item is files, in answer it counts letter typed as "files". Is it ok? See images above.
When i setup: "Require attachments" to a number where it shows "Maximum file size:"?
Is  there any place where i can see it working?
Even not working well, tanslation to PT-PT is done in AMOS. **Thanks again for the plugin**.

**Comment by gbateson** [comment]
> Is it possible have a question like i want? File and answer?
No. Please split your question into two separate questions with this question type.
One question will receive the online text; the other question will receive the PDF file.
Thanks for the PT-PT translation 👍
