### ISSUE TITLE
Fix phpunit

### ISSUE THREAD

**Issue by ewallah** [gbateson/moodle-qtype_essayautograde#37]
The file tests/walkthrough_test.php contains the function test_editorfield with 1 parameter ($editofieldname)

PHPUnit functions that are tests should have no parameters and start with test_. This function has a parameter and is not a test function.

So changing the function to something like `protected function check_editorfield($editofieldname) {}` will fix the error you see in [travis](https://travis-ci.org/github/gbateson/moodle-qtype_essayautograde/jobs/713557409#L387)

**Comment by gbateson** [comment]
Thanks ewallah. I'll try the solution you suggest.

**Comment by gbateson** [comment]
I've implemented the suggested patch and commited the new code to the repository. Let's see if it works!

**Comment by gbateson** [comment]
Oh dear, we got more errors. Can you help fix them?
https://travis-ci.org/github/gbateson/moodle-qtype_essayautograde/builds/721234068

**Comment by ewallah** [comment]
https://travis-ci.org/github/ewallah/moodle-qtype_essayautograde/jobs/722652470#L1290 is proving that phpunit and Behat can run without errors in Moodle versions 37+.

Line 113 of question test is asserting (this->assertTrue) that and empty array equals (is_same_response) an array with answer 'Once upon a time'. If this would be true, then the essayautograde question would be easy: any empty answer would be evaluated good.

So most assertTrues in the function have to be replaced by assertFalses.  Have a look at https://github.com/ewallah/moodle-qtype_essayautograde/blob/master/tests/question_test.php

**Comment by gbateson** [comment]
Hi ewallah,
thanks as always for your ongoing updates to the automated-testing funtionality in the qtype_essayautograde question type. I think the recent fix for issue #50 also fixes #37, so I will close them both now. Please reopen if necessary.
Kind regards
Gordon
