### ISSUE TITLE
show sample appearing multiple times

### ISSUE THREAD

**Issue by engrajabbar** [gbateson/moodle-qtype_essayautograde#38]
![image](https://user-images.githubusercontent.com/70248820/91250093-5d52b200-e797-11ea-992a-43c7efbaa1fb.png)

**Comment by gbateson** [comment]
I cannot duplicate this behavior, so please can you set up a sample question on my research server:

- URL: https://bateson.kochi-tech.ac.jp/37/
- Course: Course Fullname 101
- Username: guestteacher
- Password: taskchainv09

**Comment by engrajabbar** [comment]
I tried above, it is behaving ok on your site. I removed the Sample Response and put it back and it is showing now only one.

**Comment by gbateson** [comment]
Thanks for trying that. I'm glad to know that your question is now working as you expect.
