### ISSUE TITLE
MDL-68562 added a file-size limit to attachment files

### ISSUE THREAD

**Issue by ewallah** [gbateson/moodle-qtype_essayautograde#41]
As a result of the changes introduced by MDL-68562, I see exceptions during backup and restore of essayautograded questions:
Notice: Undefined property: stdClass::$maxbytes in [dirroot]/question/type/essay/edit_essay_form.php on line 100

So I presume the changes by commit https://github.com/moodle/moodle/commit/9dea33e8d0b6de51c595619d5f2990df0530ed5f will have to be added here also (for versions 3.10+).

**Comment by gbateson** [comment]
Thanks as always ewallah.

I have added the 'maxbytes' field to the options table for this qtype.
Please update this plugin on your Moodle site at the next convenient opportunity.

Regards
Gordon

**Comment by ewallah** [comment]
Small [typo](https://github.com/gbateson/moodle-qtype_essayautograde/commit/97811ed7c9b96b009c1506b35df7f66911ca92a7#diff-cb51c63dd6df37f0269dcf20e8afa7615695db0bba910c38c728196803766e35R64) in your commit:

`$q->maxbytes = 0:  `

should be 

`$q->maxbytes = 0;`
