### ISSUE TITLE
Version for Moodle 3.10 in Moodle plugins database?

### ISSUE THREAD

**Issue by germanvaleroelizondo** [gbateson/moodle-qtype_essayautograde#46]
Hi Gordon.

I hope you are OK in spite of the current COVID pandemic. Japan seems to have controlled the disease quite well.

There is no Moodle 3.10 version for this plugin available for download in the Moodle plugins database at https://moodle.org/plugins/stats.php?plugin=qtype_essayautograde

But I am sure it would be very appreciatted by many Moodlers.

It would be great if you can do the necessary tests and mark thie plugin as also available for Moodle 3.10.x

**Comment by germanvaleroelizondo** [comment]
Hi Gordon.
I can see that your plugin has Moodle 3.10 as version available in Moodle plugins database :)
Will you be testing for the soon to be released Moodle 3.11 ?
Thanks in advance.

**Comment by gbateson** [comment]
Hi German,
thanks for this nudge ;-)
I have updated the Moodle repository to show that the latest version of this plugin is compatiable with Moodle 3.11
Regards
Gordon

**Comment by germanvaleroelizondo** [comment]
Thank you Gordon :)
