### ISSUE TITLE
This question type should not force a regrade when a question is edited

### ISSUE THREAD

**Issue by timhunt** [gbateson/moodle-qtype_essayautograde#47]
Having the [regrade_question function](https://github.com/gbateson/moodle-qtype_essayautograde/blob/58f1f409550d8faad44b1617f61bcdd395d59f87/questiontype.php#L431) really goes against the design of how Moodle is intended to work. For every other question type, the way it works is: you can edit the question after it has been attempted, but scores for existing quiz attempts do not changed unless, and until, the teacher chooses to re-grade the quiz, and they get a chance to do a dry run first to see the effect of the regrade before anything is chaged.

I don't think it is a good idea for one question type to do something different, however much users might want it. (The right way to implement this feature would be in Moodle core, working for all question types.)

Also, the code implementing this has some issues:

* When finding which attempts to regrade, it only considers quizzes, not any other activity type which uses questions.
* The way it finds which attempts to regragde ignores random questions.
* Then, when it does the regrading, it regrades all the questions in the attempt, even if they are not essayautograde. That is definitely wrong.
* And, there is no option to disable this, for people who want the standard Moodle behaviour. (There is a $regrade boolean variable in the code, but it is always true).
* Finally, this code will definitely stop working once these changes happen in Moodle 4.0: https://moodle.org/mod/forum/discuss.php?d=417599#unread

**Comment by gbateson** [comment]
Thanks a lot Tim, for this analysis and information.

The functionality was useful for me when I was developing the question type, but having understood the wider context, which you have kindly described, I can see that I should remove the "regrade_question()" method from this question type.

I have removed the call to the "regrade_question()" method.
