### ISSUE TITLE
setUp() and tearDown() functions must be compatible

### ISSUE THREAD

**Issue by ewallah** [gbateson/moodle-qtype_essayautograde#48]
The setUp and tearDown functions in the file question/type/essayautograde/tests/questiontype_test.php must be compatible with the  PHPUnit\Framework\TestCase::setUp() and PHPUnit\Framework\TestCase::tearDown() functions, otherwise PHPUnit throws fatal errors:

```
Fatal error: Declaration of qtype_essayautograde_test::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in question/type/essayautograde/tests/questiontype_test.php on line 42

Fatal error: Declaration of qtype_essayautograde_test::tearDown() must be compatible with PHPUnit\Framework\TestCase::tearDown(): void in question/type/essayautograde/tests/questiontype_test.php on line 46


```
Bad:

```
    protected function setUp() {
        $this->qtype = new qtype_essayautograde();
    }

    protected function tearDown() {
        $this->qtype = null;
    }

```
Good:
```
    protected function setUp(): void {
        $this->qtype = new qtype_essayautograde();
    }

    protected function tearDown(): void {
        $this->qtype = null;
    }

```

**Comment by gbateson** [comment]
Thanks ewallah,
for reporting this issue and showing how to resolve it 

The code has been modified according to your suggestion.
Please download the new version at the next convenient opportunity, and let me know if there are still problems.

regards
Gordon
