### ISSUE TITLE
Set target min and max item count

### ISSUE THREAD

**Issue by samuel-rosa** [gbateson/moodle-qtype_essayautograde#49]
The essay (auto-grade) question type plugin is just great. I have been using it in every one of my five courses. In all of them, my interest is that the students enter a text with a given number of target words/phrases.

The only functionality that I am missing in this plugin is the ability to set target minimum and maximum item count. For example, the text entered by a student must have between say 150 and 300 words. If the item count is beyond those limits, then the submission would be penalized. Alternatively, the limits could be used in the text editor, preventing the student to submit the text if it is beyond those limits.

Perhaps this functionality is already implemented. However, I have not been able to find how to set it.

I am happy to provide more details to clarify my request.

PS.: I will start the translation to Brazilian Portuguese.

**Comment by gbateson** [comment]
Hi Samuel,
thanks for starting the Brazillian Portuguese translation 👍

I think "Grade bands" can help you.
 0 - 149 words => 0%
 150 - 200 words => 50%
 200 - 300 words => 100%
 300 - 1000 words => 0%
It won't stop the students entering too much text, but they will be penalized for sending you over 300 words.

Does that help?

**Comment by gbateson** [comment]
By the way, I notice that in Moodle 3.11 and later, the Essay question has min/max word counts, and these are inherited by the Essay (auto-grade) question. However, they are not enforced. Perhaps we could adapt that behavior? I'll think about that ...

**Comment by samuel-rosa** [comment]
@gbateson I will try to set the grade bands and see how it works. But it does look like the way to go. I am only wondering how this affects the grades awarded by the target phrases. In my exercises, there usually are about 20 target phrases with equal weights. I will run some tests to see how this works.

I think using the same behaviour of the Essay question would be a more elegant solution. I hope that you have time to do it.

**Comment by gbateson** [comment]
Hi Alessandro,

You said ...
> I think using the same behaviour of the Essay question would be a more
elegant solution

I checked the behavior of the Essay question, and actually it doesn't try
to block you from typing in more the max or less than the min. The only
change is that when the teacher is marking the Essay, there is a notice to
say that "This essay has fewer than the minimum amount of words", or "...
more than the maximum number of words". I think you are expecting something
more forceful and automatic, right?

Kind regards
Gordon

**Comment by samuel-rosa** [comment]
Hi @gbateson you are correct. I would like the question to prevent a student to submit the text if the item count is outside of the limits.

I am now looking into the grade bands that you mentioned. After a bit of reading, I am starting to think that this an even better solution. The student can still write a longer text to try to hit all target phrases, but this will penalize their submission. This means that they will have to make a decision by themselves, find a tradeoff. I am starting to like this idea.

Best.

**Comment by samuel-rosa** [comment]
I think that I did not understand how the grade bands work. Does it overwrite the grades awarded by target phrases? For instance, I set up the bands that you described above and entered a text with none of the target phrases. Still, the grade was 100% when I entered 200 words.

Please let me know if I am not being clear.

**Comment by samuel-rosa** [comment]
I read the documentation again. I think that now I understand how it works. Based on the examples provided in the documentation, I understand that the grades awarded by grade bands and target phrases are summed. Before I thought that they were multiplied. For example, if the text has all target phases, but is too long, then it would be penalized using the percentage defined in the grade bands.

I now see that I was expecting the grade bands to function as penalty factors. This would be a significant enhancement of the plugin.

**Comment by germanvaleroelizondo** [comment]
If you want to use penalty factors, you can use the glossary of common errors as explained in https://docs.moodle.org/311/en/Essay_(auto-grade)_question_type#Glossary_of_common_errors .

**Comment by gbateson** [comment]
Hi Samuel,
as German said, you can penalize specific phrases, if you use the Glossary of common mistakes. However, I think that is not quite what you are looking for.

You want to penalize an excessive number of words, right? In that case, there is another intresting technique using grade bands.

As well as specifying a 100% grade band for the ideal length, you specify a 0% grade band for the maximum length of essay that you will accept. Please see the following example:

- Award partial grades? YES

- For 0 items, award 0%
- For 150 items, award 100%
- For 300 items, award 100%
- For 400 items award 0%

Using the above settings, essays of over 300 words will score progressively less points, and essays of 400 words or more will be award 0%. This means that it is not necessary to specify a negative grade band. 

Please try that out, and let me know what you think.

Kind regards,
Gordon

**Comment by samuel-rosa** [comment]
Hi @gbateson, you are correct. I "want to penalize an excessive number of words" AND award points for the presence of a set of target phrases. I will try your suggestion and see how it works.

**Comment by samuel-rosa** [comment]
I think that this does not answer my needs. I will try to provide a clearer description.

My goal is that the students submit a text containing, say:

* between 150 and 300 words AND
* five target phrases/terms.

The student should get the maximum score (100%) if and only if both conditions are met.

If the student submits a text with say 450 words that contain all five target phrases/terms, the score should not be 100%. Instead, the score should be penalized for the excess of words, for example, 50%. The reason for using such a penalty is that the longer the text submitted, the larger the probability of it containing the target phrases/terms. My goal is that the students be concise and right to the point when submitting their essays.

Note that other penalty (or award) factors could be used such as the fog index and lexical density.

**Comment by gbateson** [comment]
I see. We are close to where you want to be. To go the final distance we need to know what percent each phrase is worth. Let's say each phrase is worth 10%. Together the five phrases account for 50% of the grade. That means that the word-count portion of the grade should be set to 50%. Therefore, the following settings will achieve what you have described:

Target phrases
1. If [phrase1] is used, award [10%]
2. If [phrase2] is used, award [10%]
3. If [phrase3] is used, award [10%]
4. If [phrase4] is used, award [10%]
5. If [phrase5] is used, award [10%]

Grade bands
- Award partial grades? YES
- For 0 items, award 0%
- For 150 items, award 50%
- For 300 items, award 50%
- For 450 items award 0%

At the moment, automatic grading baed on statistics is not possible. I fear the interface would get very cluttered if we tried to do that.

**Comment by samuel-rosa** [comment]
@gbateson I think that this is a way to fulfil my needs. But instead of 50-50, I think that it would be wiser to set 70-30 or something the like. Otherwise, students would still get 50 points even if no target phrase was in their text.

I suppose that setting 70-30 instead of 50-50 still would work in your example. As far as I understood, grades awarded by target phrases and grade bands are summed together to get the final grade. Is this correct?

**Comment by gbateson** [comment]
Hi Alessandro,

You asked:
> grades awarded by target phrases and grade bands 
> are summed together to get the final grade. 
> Is this correct?

Yes, that's exactly how the final grade is calculated. Since you have 5 target phrases, you could award 5% for each of those, and the remaining 75% for the number of words.

**Comment by gbateson** [comment]
Hi Alessandro,
further to your initial suggestion, I have modified the bavior of the plugin, so that in Moodle 3.11 and later the maximum and minimum word limits will be displayed on the input screen, along with a warning message to inform the user if the current word count is less than the minimum or more than the maximum.

I will close this issue now, but please feel free to reopen it, if you feel your concerns have not been adderssed.

Best regards
Gordon
