### ISSUE TITLE
Add more demo questions

### ISSUE THREAD

**Issue by germanvaleroelizondo** [gbateson/moodle-qtype_essayautograde#5]
Hi Gordon,

I took the liberty of forking one of your questions and edited it to make a medical question in

 https://bateson.kochi-tech.ac.jp/34/question/preview.php?id=792&previewid=238&courseid=2&variant=1&correctness=1&marks=1&markdp=2&feedback=1&generalfeedback=1&rightanswer=1&history=0

I am very excited about the opportunity of using your question type for both formative and summative assessment in my subject (veterinary pathology) at my University.

[questions-Essayautograde-Medical questions-20180730-1143.zip](https://github.com/gbateson/moodle-qtype_essayautograde/files/2242146/questions-Essayautograde-Medical.questions-20180730-1143.zip)

**Comment by gbateson** [comment]
Oh, I like it!

What language will your students be writing their essays? I think some of the PHP code assumes English, but eventually I hope to make the plugin language neutral.

**Comment by germanvaleroelizondo** [comment]
We use mexican Spanish.

[preguntas-Essayautograde-Spanish demo questions-20180731-0823.zip](https://github.com/gbateson/moodle-qtype_essayautograde/files/2245429/preguntas-Essayautograde-Spanish.demo.questions-20180731-0823.zip)

I am enclosing a working Spanish translation of your demo question. 

If you click on 'Mostrar ejemplo', copy the sample text, hide the example and paste the sample text as your answer and finish and grade, you get a nice demostration of how well your question works in Spanish.

Syllable counting may be quite similar to English (or may not be?).

**Comment by germanvaleroelizondo** [comment]
Hi Gordon.

Did you fix the error on with question import for this plugin ?

I would like to be able to import some English and Spanish qustions for medical students and some other demo questions for K-12 into your demo site.

**Comment by germanvaleroelizondo** [comment]
I am enclosing a working Medical question in Spanish:

[Medical questions in Spanish-20180731-1026.zip](https://github.com/gbateson/moodle-qtype_essayautograde/files/2245959/Medical.questions.in.Spanish-20180731-1026.zip)

**Comment by gbateson** [comment]
The error is caused by the fact that this plugin does not currently support import/export of XML file.
I think if you try export/import of GIFT file format, you will have more success.
