### ISSUE TITLE
Count of syllables in function count_syllables is  significatly wrong

### ISSUE THREAD

**Issue by drachels** [gbateson/moodle-qtype_essayautograde#52]
Recently, in file, question.php, I was testing, protected function count_syllables($word), when I realized that the function was making a significant number of errors with one syllable words that end with the letter E. To duplicate,:

- add, print_object($count); just before, return $count; in the question.php file about line 977
- preview an essay (autograde) question
- enter a list of one syllable words ending in e, such as: have knave save suave cave rave
- submit the question for grading
- notice that each of those words returns a syllable count of 2

Looking at the switch code, just before the return, the case 'E' never gets used because just above, all the words ending with 'E' letters, get them removed before the switch looks for 'E'.
I see that the count for words ending in 'Y' are also wrong for a significant number of words. If you enter, say bay may by, only the word, by, will return a 1. Say, bay, and may, will each return a 2.

**Comment by gbateson** [comment]
From what I have researched online, the only reliable way to count syllables is to use a dictionary that explcitly states how many syllables each word has.

Do you have any suggestions for efficient ways to calculate syllables for any given word?

**Comment by gbateson** [comment]
The "SyllableCount()" method in the following class maybe helpful ...
https://github.com/DaveChild/Text-Statistics/blob/master/src/DaveChild/TextStatistics/Syllables.php

**Comment by drachels** [comment]
Personally, I think I can live with results like your string that says, "Note that the algorithm for determining the number of syllables yields only approximate results.", as long as it is pretty close. I was just worried that a typical school students writing includes so many one syllable words ending in 'e' that the syllable count is going to be thrown significantly off.

I have been playing around with rearranging the code in the current count_syllables function so that I am getting better results, but still getting a few unexpected errors.

I spent a good bit of time today looking at the various links you have embedded in the count_syllables function like the one you list above. If I make any headway in adapting that, I will let you know.

Right now, I have to quit for the day, but tomorrow, after I clean out all my extra debugging garbage, i will post what I have currently.

**Comment by drachels** [comment]
Sorry, have not been able to clean up my code and post here. Got stuck with doing a couple of, "Honey do's" around the house that took all day. Will try again tomorrow.

**Comment by drachels** [comment]
Late start today due to another, "Honey do!"

I was just looking at the reference link in the count syllable function, line 969. You have a difference in your code where you place the, adjust count for special last char, last in the function, after, detect syllables for single-vowels. The code referenced in the link has those two reversed. They way you have it, the 'E' as a last letter never gets executed, like it does in the referenced code.

I have even gone so far as to put the, adjust count for special last char, before the double-vowel check. Was getting better overall results with that arraignment, along with a couple of other additions.

Here is the code I am currently using. Before changing to this code, a preview of the essay (autograde) question with the three words, have save rave, would report 6 syllables. With the following code, it reports 3.

    /**
     * count_syllables
     *
     * based on: https://github.com/e-rasvet/sassessment/blob/master/lib.php
     */
    protected function count_syllables($word) {
    //public static function count_syllables($word) {
        // https://github.com/vanderlee/phpSyllable (multilang)
        // https://github.com/DaveChild/Text-Statistics (English only)
        // https://pear.php.net/manual/en/package.text.text-statistics.intro.php
        // https://pear.php.net/package/Text_Statistics/docs/latest/__filesource/fsource_Text_Statistics__Text_Statistics-1.0.1TextWord.php.html
        $str = strtoupper($word);
        $oldlen = strlen($str);
        if ($oldlen < 2) {
            $count = 1;
        } else {
            $count = 0;
            // Adjust count for special last character.
            switch (substr($str, -1)) {
                case 'E': $count--; break;
                case 'Y': $count--; $count = max($count, 0); break;
            };
            
            // Detect syllables for double-vowels. Added the missing double-vowels with a Y.
            $vowels = array('AA','AE','AI','AO','AU','AY',
                            'EA','EE','EI','EO','EU','EY',
                            'IA','IE','II','IO','IU','IY',
                            'OA','OE','OI','OO','OU','OY',
                            'UA','UE','UI','UO','UU','UY',
                            'YA','YE','YI','YO','YU','YY');
            $str = str_replace($vowels, '', $str);
            $newlen = strlen($str);
            $count += (($oldlen - $newlen) / 2);
            
            // Detect syllables for single-vowels. Added the missing Y.
            $vowels = array('A','E','I','O','U','Y');
            $str = str_replace($vowels, '', $str);
            $oldlen = $newlen;
            $newlen = strlen($str);
            $count += ($oldlen - $newlen);
        }
        // Catch any instance where we have wound up with zero or negative count and make it a one.
        $count = max($count, 1);
print_object($count);
        return $count;
    }

**Comment by gbateson** [comment]
Thanks for sharing this code.

I see what you mean about the need to put the "case 'E': $count--; break;" before the gets removed in the 2nd "str_replace(..)". I'll move that switch block.

I don't think we need the max($count, 0) in the case "Y" statement because at that point in the code, the $count variable would always be "0". Therefore, we can just remove the case "Y" statement.

In your code, I think the switch block should be moved to after the double-vowels have been removed, so that the final "E" doesn't interfere with that calculation for double-vowels.

In the Essay (auto-grade) plugin, this code is only used to recognize words of 3 or more syllables, so I am not too worried about very short words of one or two syllables.

I would like to create a list of problematic words so that we can test the accuracy of any code that arises from this discussion.

**Comment by gbateson** [comment]
When I look more closer at the code, I think we can improve it and iprove readability at the same time, using the "count" parameter for the "str_replace()" function. As you suggest, we include "y" as a fully-fledged vowel. Also, we cache the $finalletter, so that we can test for final "e" at the end.

Here's the current version of the code that I am considering for public release:

`
    /**
     * count_syllables
     *
     * based on: https://github.com/e-rasvet/sassessment/blob/master/lib.php
     */
    protected function count_syllables($word) {
        $str = strtoupper($word);
        $strlen1 = strlen($str);
        if ($strlen1 < 2) {
            $count = 1;
        } else {
            $count = 0;

            // detect syllables for double-vowels
            $vowels = array('AA','AE','AI','AO','AU','AY',
                            'EA','EE','EI','EO','EU','EY',
                            'IA','IE','II','IO','IU','IY',
                            'OA','OE','OI','OO','OU','OY',
                            'UA','UE','UI','UO','UU','UY');
            $vowelcount = 0;
            $str = str_replace($vowels, '', $str, $vowelcount);
            $count += $vowelcount;

            // Cache the final letter, in case it is an "e"
            $finalletter = substr($str, -1);

            // detect syllables for single-vowels
            $vowelcount = 0;
            $vowels = array('A','E','I','O','U','Y');
            $str = str_replace($vowels, '', $str, $vowelcount);
            $count += $vowelcount;

            // adjust the count for words that end in "e"
            // and have at least one other vowel
            if ($count > 1 && $finalletter == 'E') {
                $count--;
            }
        }
        return $count;
    }
`

**Comment by drachels** [comment]
You are right that the switch case block might be better where you have moved it. I had been trying it in both spots and did not notice any difference in accuracy.

The reason for the max($count, 0) in the 'Y' case was because I was using $count--, just like I was for the 'E' case. I was printing the results and noticed that some words would get the $count down to -1. The max($count, 0) was there to correct for that. It was giving good results on all the words ending in y that I checked.

As for creating a list of _problematic words_, I have started doing so by creating and new, public static function problem_words($word). I have put the same array of words in it, that you sent me the link for the other day. I'm tempted to try and turn it into a file, that an admin or teacher could add to, and then read into my plugin. Basically do it the same way I add new lessons and exercises into the MooTyper plugin.

Now to go see if I can add and use the other arrays:

- syllables would be counted as two but should be one
- syllables would be counted as one but should be two
- Single syllable prefixes and suffixes
- Double syllable prefixes and suffixes
- Triple syllable prefixes and suffixes

**Comment by drachels** [comment]
I think you are going to want to adapt to using the problem word array. With the words in it already, plus two more I've added, with my code I get 150 total syllables. With the code you have listed above, I get only 107. The list does contain quite a few pretty common words.

**Comment by gbateson** [comment]
Would you care to share a list of words you have found whose syllable count is measured wrongly by the most recent version of  the “count_syllables()” function that I have posted in this thread? That would really help me.

**Comment by drachels** [comment]
Here is a list of problem words that you can copy and paste.
abalone
abare
abed
abruzzese
abbruzzese
aborigine
acreage
adame
adieu
adobe
anemone
apache
aphrodite
apostrophe
ariadne
cafe
calliope
catastrophe
chile
chloe
circe
coyote
epitome
forever
gethsemane
guacamole
hyperbole
jesse
jukebox
karate
machete
maybe
people
recipe
sesame
shoreline
simile
syncope
tamale
yosemite
daphne
eurydice
euterpe
hermione
penelope
persephone
phoebe
zoe

**Comment by drachels** [comment]
Here is a list of the same words with their correct syllable count.
         'abalone'          => 4
        ,'abare'            => 3
        ,'abed'             => 2
        ,'abruzzese'        => 4
        ,'abbruzzese'       => 4
        ,'aborigine'        => 5
        ,'acreage'          => 3
        ,'adame'            => 3
        ,'adieu'            => 2
        ,'adobe'            => 3
        ,'anemone'          => 4
        ,'apache'           => 3
        ,'aphrodite'        => 4
        ,'apostrophe'       => 4
        ,'ariadne'          => 4
        ,'cafe'             => 2
        ,'calliope'         => 4
        ,'catastrophe'      => 4
        ,'chile'            => 2
        ,'chloe'            => 2
        ,'circe'            => 2
        ,'coyote'           => 3
        ,'epitome'          => 4
        ,'forever'          => 3
        ,'gethsemane'       => 4
        ,'guacamole'        => 4
        ,'hyperbole'        => 4
        ,'jesse'            => 2
        ,'jukebox'          => 2
        ,'karate'           => 3
        ,'machete'          => 3
        ,'maybe'            => 2
        ,'people'           => 2
        ,'recipe'           => 3
        ,'sesame'           => 3
        ,'shoreline'        => 2
        ,'simile'           => 3
        ,'syncope'          => 3
        ,'tamale'           => 3
        ,'yosemite'         => 4
        ,'daphne'           => 2
        ,'eurydice'         => 4
        ,'euterpe'          => 3
        ,'hermione'         => 4
        ,'penelope'         => 4
        ,'persephone'       => 4
        ,'phoebe'           => 2
        ,'zoe'              => 2

**Comment by drachels** [comment]
In your file question.php, just before the, return $count, in the function count_syllables, I added a print object like this:
        print_object('The word is '.$word.' and the count is '.$count);
In the same file, just before the return in, function get_stats_uniquewords, I added this:
        print_object('Total syllabels: '.$total);
I then run my one question sample quiz and past the first list of words, then start comparing. You will see a lit of miscounts and a total of 107 that should be 146. On mine I see 150 total as I added two more problem words.

**Comment by drachels** [comment]
I have temporarily cobbled together both your syllable count and the one by Dave Child and have them both printing out the word and syllable count so that we have a direct comparison of results. If you are interested in taking a look go to 
http://www.drachels.com/moodle311/login/index.php
Log in as student1 with pswd of, test, to see the students view. Go to course, Diary Development, check the first Diary activity in topic 1. 
Log in as teacher3 with pswd of, test. Go to the same course and activity, then click on the link over to the right that is currently saying, View 23 diary entries.
The Dave Child code still needs lots of TLC to make it meet Moodle coding requirements/styles, but I am getting subtle hints from my wife I've worked overtime today, so gotta quit for now.

**Comment by gbateson** [comment]
Thanks for the list, I have categorized them and added few more from my own investigations.
Please see the attached file.

[ESSAY-AUTO-GRADE.syllable-word-list.txt](https://github.com/gbateson/moodle-qtype_essayautograde/files/6846183/ESSAY-AUTO-GRADE.syllable-word-list.txt)

**Comment by drachels** [comment]
Hi Gordon,
I am sorry to say that it has been a somewhat bad month for my wife so I have not been able to spend hardly any time on this up until just yesterday.
I have made the couple of minor changes to make sure the syllable count function I originally copied from your code is the same as what I you currently have. I am running it in comparison to the code from Dave Child and continue to see quite a few differences. The word list you provided in your last reply...are you using it anywhere in your code?

**Comment by gbateson** [comment]
Since your orginal post, I have spent quite a while exploring different algorithms to "calculate" the syllable count of English words by counting the vowel clusters and then trying to compensate for the final "e" anomalies, the treatment of "y" and "qu", as well as trailing "ier" and "iest". However, I have formed the view that such code is easily duped, for example by plural forms of nouns and past tense forms of verbs.

The only way to reliably count syllables is with a dictionary, such as https://github.com/gautesolheim/25000-syllabified-words-list/. Dictionaries for languages other than English are also available on the web.

In the case of the Essay (auto-grade) question type, it is not necessary to count syllables accurately, so I will not try to improve the syllable-counting algorithm at the current time.

In the long-term, I would like to incorporate dictionaries into qtype_essayautograde. I intend to have the software download a suitable dictionary for the target language and then cache it in the Moodle database.

I wish you luck with your diary plugin, and, more importantly, I hope you and your wife have more good days than bad days in the future so that you can occasionally find some respite from what seems to be the difficult circumstances of your daily lives.

I will close this issue now, but please reopen it if you feel there is more to discuss.
