### ISSUE TITLE
Getting this error message when trying to edit essayautograde question.

### ISSUE THREAD

**Issue by kamiobi2** [gbateson/moodle-qtype_essayautograde#61]
エラー
error/サーバとの通信中にエラーが発生しました。
Debug info:
Error code: サーバとの通信中にエラーが発生しました。
$a contents:
Stack trace:
line 159 of /lib/classes/session/manager.php: core\session\exception thrown
line 139 of /lib/classes/session/manager.php: call to core\session\manager::start_session()
line 808 of /lib/setup.php: call to core\session\manager::start()
line 29 of /config.php: call to require_once()
line 44 of /mod/quiz/edit.php: call to require_once()

**Comment by gbateson** [comment]
What version of Moodle are you using?
When did this problem start?
When did you upgrade or install the Essay (auto-grade) plugin?
Does this error occur for all essayautograde questions? Or just one?

**Comment by gbateson** [comment]
Hi there kamiobi2,
would you like to continue investigating this error? If so, please reopne the issue on github.com and let's conversation there.
Best regards,
Gordon
