### ISSUE TITLE
MDL-76849 has to be implemeted.

### ISSUE THREAD

**Issue by ewallah** [gbateson/moodle-qtype_essayautograde#68]
Changes introduced by MDL-76848 have to be implemented. In the tests it is already clear that there was a big change, so a lot of errors are generated, 

PHPUnit tests can be fixed by adding this before line 65: $renderer->set_displayoptions($options);

Fixing the Behat add_feature tests will take more work.

**Comment by gbateson** [comment]
Great! Thanks ewallah, for the fix to the display options
