### ISSUE TITLE
Moodle Docs page

### ISSUE THREAD

**Issue by germanvaleroelizondo** [gbateson/moodle-qtype_essayautograde#7]
Hi Gordon,

I hope you don't mind that I created a Moodle Docs  page for your plugin at https://docs.moodle.org/34/en/question/type/essayautograde. It is linked when you click on the 'Moodle Docs for this page' when editing at your demo site (Moodle 3.4).

Please feel free to add, remove or change as you see fit.

**Comment by gbateson** [comment]
Wow, what a great page! Thank you so much.
I love that you used the word "awesome" a lot on that page - thanks!

**Comment by gbateson** [comment]
Maybe we could take out the Javascript from the question text.
It looks a bit daunting - especially for beginners.
Eventually, it will be replaced by your suggested functionality of a sample essay ;-)

**Comment by germanvaleroelizondo** [comment]
I am very happy that you will add the optional sample essay functionality.

In the meantime, because it is only a copy/paste instruction, I do not think average K-12 teachers would find it disturbing, but maybe I should add a simpler example first, before that awesome one :-)

**Comment by gbateson** [comment]
Hi German,
I added the "Sample response" functionality to the Essay (auto-grade) question type.
You'll notice I also added the "Glossary of common errors" functionality.
If you have time, please could you update the documentation, and the Spanish lang packs.
Many thanks,
Gordon

**Comment by germanvaleroelizondo** [comment]
Hi Gordon,

I will update the Moodle Docs as soon as I get home today.
I will also update the Spanish language packs.

I am very excited that your plugin keeps on improving more and more. 

Maybe you can talk to the Moodle Association of Japan, and maybe they can talk to MUA, in order to support your plugin's inclusion into Moodle core, as it just seems to be happening for another plugin according to https://outlook.office.com/mail/inbox/id/AAQkADRjNDRiY2RiLTM4OGEtNGZkOS1hNmY1LTM0Zjg5NzEyOWJhNAAQAJ10FSW%2BsnZLmCT6RP9esV0%3D  

Many, many thanks for making so many great additional plugins that help to make an even better Moodle for many of us.,

Germán

**Comment by germanvaleroelizondo** [comment]
Hi Gordon,
I tried your plugin version 2019022056
BUT I could not see the "Sample response" functionality :(
I will delete my demo 3.6.2 server and re-try again.

**Comment by germanvaleroelizondo** [comment]
Hi Gordon,
It seems that the English language strings in https://github.com/gbateson/moodle-qtype_essayautograde/tree/master/lang/en have not changed in 7 months. 

I did not see the Glossary of common errors :(

I am goind to delete my demo server and re-do everything from 0.

**Comment by germanvaleroelizondo** [comment]
Hi Gordon,

This GitHub repo shows that your last code update was 13 days ago.

Did you move your master branch elsewhere ?

**Comment by gbateson** [comment]
Hi German,
sorry for the confusion. The latest release is now available on GitHub.
Please update your local copy at the next convenient opportunity.
Many thanks,
Gordon

**Comment by germanvaleroelizondo** [comment]
Hi Gordon.

This new version is even more awesome :)

I have updated the Moodle Docs page at https://docs.moodle.org/36/en/Essay_(auto-grade)_question_type 

Please feel free to add/remove/change as you see fit. 
You are the English language teacher. I am a veterinary pathologist :)

After you have OK'ed the Docs I will add the veterinary pathology example and the Spanish language  Moodle Docs page.

I will later see the plugin's English and Spanish languages strings, make the needed changes and make a pull request.

Your work is truly amazing.

Many, many warm thanks.

Are you a member of MUA? This plugin may be a worthy cause for MUA.

Have you contacted Tim Hunt about this plugin?. It may also be a very nice addition to some O.U.'s quizzes.

Congratulations on this increasingly more awesome and useful Moodle plugin.

**Comment by germanvaleroelizondo** [comment]
I just updated the es and es_mx language strings in the latest pull request.

**Comment by germanvaleroelizondo** [comment]
Hi Gordon,

I have typed the general pathology example in the Moodle Docs page.

Now I need to re-size all the images and the Docs page will be ready for your second review/edit :)

**Comment by germanvaleroelizondo** [comment]
I have re-sized the images and added a section on the manual review of the attempts and also added some more images.

The Moodle Docs page at https://docs.moodle.org/36/en/Essay_(auto-grade)_question_type is ready for you to perform a second editing and fix the English grammar errors I have probably made :)

**Comment by gbateson** [comment]
Thank you very much Valero!

**Comment by germanvaleroelizondo** [comment]
I have added more information about using a common errors glossary in order to detect commonly plagiarized phrases.

Please have a look and add/remove/change as necessary.

The Moodle Docs page is nearly complete. After you have OKed it, I will update the Spanish Moodle Docs page and images.

**Comment by gbateson** [comment]
Wow! That's a major bit of work German. Thank you.
The insight and examples you give from your experience actually using this plugin is very useful.
You raise a good point about [First or first]. 
Do you think it would be more useful to match the text without worrying about upper and lower case?

**Comment by germanvaleroelizondo** [comment]
Hi Gordon,
I think it would be very useful and user-friendly if the key phrases and the common errors sections each had a case sensitivity checkbox, just as the core Short-answer question type.  But I do not know how difficult and time-consuming it would be for you to add them:

![Case Sensitivity checkbox](https://user-images.githubusercontent.com/2671923/55008531-bcab0200-4fa6-11e9-8646-7af27ef1f833.png)

**Comment by gbateson** [comment]
Thanks German. That's very clear.
We can do it, but it's a bit of work.
I'll see if I can find some funding :-)

**Comment by germanvaleroelizondo** [comment]
I will check the new version and change Moodle Docs accordingly.

**Comment by germanvaleroelizondo** [comment]
As the current version does not yet implement the complete/incomplete words and case sensitive/unsensitive toggles ( see issue #25), the Mooodle Docs page changes will have to wait...

**Comment by germanvaleroelizondo** [comment]
I saw the new plugin version with these new features.
Great work!
