### ISSUE TITLE
Invalid get_string() identifier: 'addsingleBAND'

### ISSUE THREAD

**Issue by ewallah** [gbateson/moodle-qtype_essayautograde#72]
[Line 789 ](https://github.com/ewallah/moodle-qtype_essayautograde/blob/master/edit_essayautograde_form.php#L789) of the edit_essayautograde_form contains the code `$type = strtoupper($type);`

As a result the code in [line 803](https://github.com/ewallah/moodle-qtype_essayautograde/blob/master/edit_essayautograde_form.php#L803) can generate wrong string identifiers: `$label = ($count == 1 ? 'addsingle'.$type : 'addmultiple'.$types);`

This can be fixed changing line 803 into `$label = ($count == 1 ? 'addsingle' . strtolower($type) : 'addmultiple' . $types);`

When I added this fix, [Behat](https://github.com/ewallah/moodle-qtype_essayautograde/actions/runs/4639562297/jobs/8210553181#step:16:134) is working again.

**Comment by gbateson** [comment]
Actually, in [line 788](https://github.com/gbateson/moodle-qtype_essayautograde/blob/master/edit_essayautograde_form.php#L788) the original code, the strtoupper() value is stored in a a variable called $TYPE not $type, so there is no problem.

Perhaps your editor or programming environment automatically "fixes" uppercase variable names to lower case? 

Anyway, I can see that using uppercase variables could be confusing, so I have removed it from the code.
