### ISSUE TITLE
Call to check_ordering_combined_feedback throws an error when ordering question is not installed.

### ISSUE THREAD

**Issue by ewallah** [gbateson/moodle-qtype_essayautograde#73]
The function check_ordering_combined_feedback is part of the question type ordering.  When this question type is not installed, the function throws an error.

Or
Comment out the code [Line 667](https://github.com/ewallah/moodle-qtype_essayautograde/blob/master/questiontype.php#L667) and  [Line 905](https://github.com/ewallah/moodle-qtype_essayautograde/blob/master/questiontype.php#L905)

Or
Add $plugin->dependencies = ['qtype_ordering' => 'any'] to the version.php file

**Comment by gbateson** [comment]
Thanks ewallah. I have added the missing function to the essayautograde question, so the import of xml and gift files should be working again.
