### ISSUE TITLE
 Xml moodle Import exception check_ordering_combined_feedback undefined

### ISSUE THREAD

**Issue by fxpar** [gbateson/moodle-qtype_essayautograde#76]
Hi Gordon, 
I get this exception when I import the same file as the xml export:
Exception : Call to undefined method qtype_essayautograde::check_ordering_combined_feedback()
My guess is that my university is on a moodle 4.2 version (not sure).
Cheers

**Comment by gbateson** [comment]
Hi Francois,
 as you say, the plugins repository on Moodle.org did not have the latest version of this plugin. I have bumped the version number and uploaded the latest version to Moodle.org. The version number is "2023-04-09 (25)". Please arrange for this plugin to be updated on your Moodle site at the earliest convenient opportunity.

Thanks for alerting me to this issue.

**Comment by fxpar** [comment]
Thank you Gordon 👍Perfect !
