### ISSUE TITLE
Minor suggested changes to improve ease-of-use for average teachers

### ISSUE THREAD

**Issue by germanvaleroelizondo** [gbateson/moodle-qtype_essayautograde#8]
Hi Gordon,

Can you please think about the possibility of making these minor changes in the plugin code:

- In the Target phrases [n]  dialogues, where it says  
Target phrase [n] .. If [target_phrase_n] is used, award [n% of the question grade], 

 change the fixed-sized input_box for  [target_phrase_n] into an expandable input box, where the user can easily click the lower right corner and drag it to enlarge into a desirable size, 
so that the teacher can easily type more complex [this OR that OR this also AND more text] long phrases.

![imagen](https://user-images.githubusercontent.com/2671923/43538025-8794f2a4-9586-11e8-9bc9-d7f575101275.png)

Also, if you think it would be sensible and not too cumbersome, also change the 'Add another target phrase' button to 'Add three more target phrases, and if the user do not need to use one or two empty target phrases, it may not cause an error, but mereley the empty boxes disappear when the teacher reopens a previously saved question instance (as other Moodle core questions do).
![imagen](https://user-images.githubusercontent.com/2671923/43538121-bca9dac2-9586-11e8-822b-6b16e4305e2f.png)

Thanks in advance.

**Comment by gbateson** [comment]
I have modified the add buttons so that you can add a selectable number of new grade bands or target phrases (see screenshot)
![essayautograde](https://user-images.githubusercontent.com/799312/43755757-815a740c-9a4c-11e8-94b5-09abcb874874.png)

**Comment by germanvaleroelizondo** [comment]
Thanks Gordon,
I will update my plugin and comment back.

**Comment by germanvaleroelizondo** [comment]
I can confirm that both changes were successful and this issue should be closed as fixed.

This is now an 'even more awesome' question type plugin.
![essay auto-grade fixed size input box now](https://user-images.githubusercontent.com/2671923/43778831-513bc120-9a1c-11e8-8ac5-72307b250481.png)

Thanks a lot, Gordon.
